Expose SoLoaderWrapper interface as public (#177)
Summary:
As from discussion in https://github.com/facebookincubator/spectrum/issues/43

This PR fixes issue when Kotlin generated code adds typecast to `SoLoaderWrapper` and this causes `IllegalAccessError` at run time as classes can't access package private `SoLoaderWrapper` interface.

**Kotlin:**
```
SpectrumSoLoader.init(context, SpectrumSoLoader.SystemSoLoaderImpl())
```

**Generated:**
```
SpectrumSoLoader.init((Context)context, (SoLoaderWrapper)(new SystemSoLoaderImpl()));
```

**Run-time error:**
```
java.lang.IllegalAccessError: Illegal class access: 'com.example.SpectrumLoader' attempting to access 'com.facebook.spectrum.SpectrumSoLoader$SoLoaderWrapper' (declaration of 'com.example.SpectrumLoader' appears in /data/app/com.example.dev-ZTjIGlrpJnf4A8NSyFKk4g==/split_lib_slice_2_apk.apk)
```
Pull Request resolved: https://github.com/facebookincubator/spectrum/pull/177

Reviewed By: diegosanchezr

Differential Revision: D16262267

Pulled By: cuva

fbshipit-source-id: 0b34f5c4446b36e7d63e5043f98bbe4ad6d8e972